name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  xrefcheck:
    name: Check references
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: serokell/xrefcheck-action@v1

# TODO: Use https://github.com/marketplace/actions/github-codeowners-validator
